# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb9ba9780fe4e38d9f39f59d8cdd139ca49e53f64b551ef7a8a72da322d0e7de9273ffa9bfcf3ef3c48939193512a75c20364ed4f14c8c7f80d19b35a4281577

test:
  secret_key_base: f16a6a4905c414ab7317a2b47b3c4974b4603960db5e37d6b77baae894986f24ae00aef09a537815b9a748b67c82e5d61ae2abe5aabed855b46d123b5d6c7e0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
